# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  build:
    working_directory: /app
    docker:
      - image: docker:git
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - restore_cache:
          keys:
            - docker-cache
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i /caches/app.tar | true
      - run:
          name: list
          command: |
            ls
      - run:
          name: Build Docker image
          command: |
            docker build --cache-from=app -t app ./hotel-fe
      - run:
          name: Save Docker image caches
          command: |
            mkdir -p /caches
            docker save -o /caches/app.tar app
      - save_cache:
          paths:
            - /caches/app.tar
          key: docker-cache
      - deploy:
          name: Push docker image
          command: |
            echo "$dockerhub_password" | docker login -u "$dockerhub_username" --password-stdin
            docker tag app dinhlockt02/hotelmanagement_frontend-prods
            docker push dinhlockt02/hotelmanagement_frontend-prods
  deploy_vps:
    working_directory: ~/project
    docker:
      - image: cimg/base:2022.03
    steps:
      - run: echo $AWS_KEY | base64 -d > aws_key.pem
      - run: chmod 400 aws_key.pem
      - run: cat aws_key.pem
      - run: ssh -o "StrictHostKeyChecking=no" -i "aws_key.pem" $SSH_HOST
      - run: echo $PWD
workflows:
  build-workflow:
    jobs:
      - deploy_vps
